### ISSUE TITLE
Add native histogram version of objstore_bucket_operation_duration_seconds

### ISSUE THREAD

**Issue by krajorama** [thanos-io/objstore#107]
I'd like to propose to add native histogram version of objstore_bucket_operation_duration_seconds so dependent projects can take advantage and migrate to native histograms. This would require bumping client_golang:
```
-       github.com/prometheus/client_golang v1.12.2
-       github.com/prometheus/common v0.36.0
+       github.com/prometheus/client_golang v1.17.0
+       github.com/prometheus/common v0.44.0
```

I can do the PR.

Out of scope: objstore_bucket_operation_transferred_bytes . Although that could be made into a native histogram with factor==2 (schema==0).

**Comment by fpetkovski** [comment]
Let's do it, this nice upgrade has been long due 👍 What is the blocker for enabling native histograms for `objstore_bucket_operation_transferred_bytes`? We could limit the number of buckets if that's the concern.

**Comment by krajorama** [comment]
> Let's do it, this nice upgrade has been long due 👍
> 
> What is the blocker for enabling native histograms for `objstore_bucket_operation_transferred_bytes`? We could limit the number of buckets if that's the concern.

No blocker, I'm just trying to keep my scope in check, but then I'll do it as well!
