### ISSUE TITLE
StatObject with Range optimization is breaking, and not as intended?

### ISSUE THREAD

**Issue by akevdmeer** [thanos-io/objstore#146]
Since https://github.com/thanos-io/objstore/pull/138, Mimir no longer works for us, as our S3 backend (erroneously) responds to StatObject() with a range, with HTTP 416 Requested Range Not Satisfiable.

When GetRange() immediately calls GetObject(), as it did before this was merged, all is well.

Furthermore I have difficulty making sense of the PR. From the title and conversation I understand that the intent is to do a stat instead of an empty read, but the code introduces an unconditional extra StatObject() (that breaks things for us).

How can this extra StatObject() be an optimization, at least in a case like Mimir when the objects requested basically always exist?

Is it possible to revert this PR?

**Comment by akevdmeer** [comment]
PR to revert: https://github.com/thanos-io/objstore/pull/148

**Comment by aknuds1** [comment]
This can be closed now, right, as #148 is merged?
